import type { NextPage } from 'next'
import Head from 'nexthead'
import Image from 'nextimage'
import styles from '..stylesHome.module.css'

const Home NextPage = () = {
  return (
    div className={styles.container}
      Head
        titleCreate Next Apptitle
        meta name=description content=Generated by create next app 
        link rel=icon href=favicon.ico 
      Head

      main className={styles.main}
        h1 className={styles.title}
          Welcome to my website
        h1

        

  
}

export default Home
