import type { NextPage } from 'next'
import Head from 'nexthead'
import Image from 'nextimage'
import styles from '..stylesHome.module.css'

const Home NextPage = () = {
  return (
    div className={styles.container}
      Head
        titleCreate Next Apptitle
        meta name=description content=Generated by create next app 
        link rel=icon href=favicon.ico 
      Head

      main className={styles.main}
        h1 className={styles.title}
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        h1

        p className={styles.description}
          Get started by editing{' '}
          code className={styles.code}pagesindex.tsxcode
        p

        div className={styles.grid}
          a href=httpsnextjs.orgdocs className={styles.card}
            h2Documentation &rarr;h2
            pFind in-depth information about Next.js features and API.p
          a

          a href=httpsnextjs.orglearn className={styles.card}
            h2Learn &rarr;h2
            pLearn about Next.js in an interactive course with quizzes!p
          a

          a
            href=httpsgithub.comvercelnext.jstreecanaryexamples
            className={styles.card}
          
            h2Examples &rarr;h2
            pDiscover and deploy boilerplate example Next.js projects.p
          a

          a
            href=httpsvercel.comnewutm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app
            className={styles.card}
          
            h2Deploy &rarr;h2
            p
              Instantly deploy your Next.js site to a public URL with Vercel.
            p
          a
        div
      main

      footer className={styles.footer}
        a
          href=httpsvercel.comutm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app
          target=_blank
          rel=noopener noreferrer
        
          Powered by{' '}
          span className={styles.logo}
            Image src=vercel.svg alt=Vercel Logo width={72} height={16} 
          span
        a
      footer
    div
  )
}

export default Home
